CREATE TABLE PART (
	P_PARTKEY		INT NOT NULL,
	P_NAME			VARCHAR(55),
	P_MFGR			CHAR(25),
	P_BRAND			CHAR(10),
	P_TYPE			VARCHAR(25),
	P_SIZE			INT,
	P_CONTAINER		CHAR(10),
	P_RETAILPRICE	DECIMAL,
	P_COMMENT		VARCHAR(23),
	PRIMARY KEY(P_PARTKEY)
);

COPY part FROM '../../simpleset/part.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE REGION (
	R_REGIONKEY	INT NOT NULL,
	R_NAME		CHAR(25),
	R_COMMENT	VARCHAR(152),
	PRIMARY KEY(R_REGIONKEY)
);

COPY region FROM '../../simpleset/region.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE NATION (
	N_NATIONKEY		INT NOT NULL,
	N_NAME			CHAR(25),
	N_REGIONKEY		INT NOT NULL,
	N_COMMENT		VARCHAR(152),
	PRIMARY KEY(N_NATIONKEY),
	FOREIGN KEY(N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);

COPY nation FROM '../../simpleset/nation.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE SUPPLIER (
	S_SUPPKEY		INT NOT NULL,
	S_NAME			CHAR(25),
	S_ADDRESS		VARCHAR(40),
	S_NATIONKEY		INT NOT NULL,
	S_PHONE			CHAR(15),
	S_ACCTBAL		DECIMAL,
	S_COMMENT		VARCHAR(101),
	PRIMARY KEY(S_SUPPKEY),
	FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

COPY SUPPLIER FROM '../../simpleset/supplier.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE CUSTOMER (
	C_CUSTKEY		INT NOT NULL,
	C_NAME			VARCHAR(25),
	C_ADDRESS		VARCHAR(40),
	C_NATIONKEY		INT NOT NULL,
	C_PHONE			CHAR(15),
	C_ACCTBAL		DECIMAL,
	C_MKTSEGMENT	CHAR(10),
	C_COMMENT		VARCHAR(117),
	PRIMARY KEY(C_CUSTKEY),
	FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

COPY CUSTOMER FROM '../../simpleset/customer.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE PARTSUPP (
	PS_PARTKEY		INT NOT NULL,
	PS_SUPPKEY		INT NOT NULL,
	PS_AVAILQTY		INTEGER,
	PS_SUPPLYCOST	DECIMAL,
	PS_COMMENT		VARCHAR(199),
	PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY),
	FOREIGN KEY (PS_PARTKEY) REFERENCES PART(P_PARTKEY),
	FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);

COPY PARTSUPP FROM '../../simpleset/partsupp.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE ORDERS (
	O_ORDERKEY		INT NOT NULL,
	O_CUSTKEY		INT NOT NULL,
	O_ORDERSTATUS	CHAR(1),
	O_TOTALPRICE	DECIMAL,
	O_ORDERDATE		DATE,
	O_ORDERPRIORITY	CHAR(15),
	O_CLERK			CHAR(15),
	O_SHIPPRIORITY	INT,
	O_COMMENT		VARCHAR(79),
	PRIMARY KEY(O_ORDERKEY),
	FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);

COPY ORDERS FROM '../../simpleset/orders.tbl' WITH (FORMAT 'tbl', DELIMITER '|');

CREATE TABLE LINEITEM (
	L_ORDERKEY		INT NOT NULL,
	L_PARTKEY		INT NOT NULL,
	L_SUPPKEY		INT NOT NULL,
	L_LINENUMBER	INT NOT NULL,
	L_QUANTITY		DECIMAL,
	L_EXTENDEDPRICE	DECIMAL,
	L_DISCOUNT		DECIMAL,
	L_TAX			DECIMAL,
	L_RETURNFLAG	CHAR(1),
	L_LINESTATUS	CHAR(1),
	L_SHIPDATE		DATE,
	L_COMMITDATE	DATE,
	L_RECEIPTDATE	DATE,
	L_SHIPINSTRUCT	CHAR(25),
	L_SHIPMODE		CHAR(10),
	L_COMMENT		VARCHAR(44),
	PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
	FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY)
);

COPY LINEITEM FROM '../../simpleset/lineitem.tbl' WITH (FORMAT 'tbl', DELIMITER '|');
ALTER TABLE LINEITEM ADD CONSTRAINT fgn_part_supp FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES PARTSUPP(PS_PARTKEY,PS_SUPPKEY);
